apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-config
data:
  MINIO_ENDPOINT: "minio-service"
  MINIO_PORT: "9000"
  MINIO_BUCKET: "uploads"
  RABBITMQ_URL: "amqp://rabbitmq-service:5672"
  RABBITMQ_QUEUE: "video-processing"
